## ALGORITMOS (KNN e RANDOM FOREST)

In [24]:
# Importação dos dados
import numpy as np
import pandas as pd

from sklearn import metrics
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [4]:
# Abertura do CSV
data = pd.read_csv('casos-covid-go.csv')
data.tail()

             date state  ... confirmed_per_100k_inhabitants death_rate
97116  2020-04-01    GO  ...                        0.45935        0.0
97117  2020-03-31    GO  ...                        0.45935        0.0
97118  2020-03-30    GO  ...                        0.45935        0.0
97119  2020-03-29    GO  ...                        0.45935        0.0
97120  2020-03-28    GO  ...                        0.45935        0.0

[5 rows x 13 columns]

In [41]:
# Filtragem nos dados
estados = data.loc[data.place_type == 'state']
estados_go = estados.loc[estados.state == 'GO']
estados_go_confirmados = estados_go.groupby('date').sum()['deaths'].reset_index()
estados_go_confirmados['date'] = pd.to_datetime(estados_go_confirmados['date'])
estados_go_confirmados.tail()

          date  deaths
468 2021-06-23   18768
469 2021-06-24   18850
470 2021-06-25   18950
471 2021-06-26   18967
472 2021-06-27   18988

In [42]:
# Separação entre treinamento e teste do data-set
atributos = ['date']
atributos_prev = ['deaths']

X = estados_go_confirmados[atributos].values
Y = estados_go_confirmados[atributos_prev].values

X_treino, X_teste, Y_treino, Y_teste = train_test_split(X, Y, test_size=0.30)

In [43]:
# KNN
# Criar a instância do modelo KNN
knn = KNeighborsRegressor(n_neighbors=4)
# Treinamento
knn.fit(X_treino, Y_treino)
# Predição
pred = knn.predict(np.array(pd.to_datetime(['2021-11-01'])).reshape(-1, 1))
pred

array([[18938.75]])

In [44]:
# Calculando o Score do KNN
knn.score(X_teste, Y_teste)

0.9998834330327696

In [48]:
# RANDOM FOREST - Regressor
#modelRF = RandomForestRegressor(random_state=42)
modelRF = RandomForestRegressor()
modelRF.fit(X_treino, Y_treino.ravel())
predicaoRF = modelRF.predict(np.array(pd.to_datetime(['2021-11-01'])).reshape(-1, 1))
predicaoRF

array([18969.87])

In [46]:
# Calculando o Score do Random Forest
modelRF.score(X_teste, Y_teste)

0.9998935106032051