##Previsão com Prophet

In [16]:
!pip install prophet

Requirement already satisfied: prophet in c:\users\aluno\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: holidays<1,>=0.25 in c:\users\aluno\anaconda3\lib\site-packages (from prophet) (0.83)
Requirement already satisfied: tqdm>=4.36.1 in c:\users\aluno\anaconda3\lib\site-packages (from prophet) (4.64.1)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\aluno\anaconda3\lib\site-packages (from prophet) (3.5.2)
Requirement already satisfied: pandas>=1.0.4 in c:\users\aluno\anaconda3\lib\site-packages (from prophet) (1.4.4)
Requirement already satisfied: numpy>=1.15.4 in c:\users\aluno\anaconda3\lib\site-packages (from prophet) (1.21.5)
Requirement already satisfied: importlib_resources in c:\users\aluno\anaconda3\lib\site-packages (from prophet) (6.5.2)
Requirement already satisfied: cmdstanpy>=1.0.4 in c:\users\aluno\anaconda3\lib\site-packages (from prophet) (1.3.0)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in c:\users\aluno\anaconda3\lib\site-packages (from cmdstanpy>=1.0.4->prophet) (0.5.1)
Requirement already satisfied: python-dateutil in c:\users\aluno\anaconda3\lib\site-packages (from holidays<1,>=0.25->prophet) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aluno\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (4.25.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\aluno\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (9.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\aluno\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\aluno\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (1.4.2)
Requirement already satisfied: packaging>=20.0 in c:\users\aluno\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (21.3)
Requirement already satisfied: cycler>=0.10 in c:\users\aluno\anaconda3\lib\site-packages (from matplotlib>=2.0.0->prophet) (0.11.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aluno\anaconda3\lib\site-packages (from pandas>=1.0.4->prophet) (2022.1)
Requirement already satisfied: colorama in c:\users\aluno\anaconda3\lib\site-packages (from tqdm>=4.36.1->prophet) (0.4.5)
Requirement already satisfied: zipp>=3.1.0 in c:\users\aluno\anaconda3\lib\site-packages (from importlib_resources->prophet) (3.8.0)
Requirement already satisfied: six>=1.5 in c:\users\aluno\anaconda3\lib\site-packages (from python-dateutil->holidays<1,>=0.25->prophet) (1.16.0)

In [27]:
#Importação das Libs
import pandas as pd
import prophet as ph

In [28]:
data = pd.read_csv('casos-covid-go.csv')
data.tail()

,date,state,city,place_type,confirmed,deaths,order_for_place,is_last,estimated_population_2019,estimated_population,city_ibge_code,confirmed_per_100k_inhabitants,death_rate
97116,2020-04-01,GO,Águas Lindas de Goiás,city,1,0,5,False,212440.0,217698.0,5200258.0,0.45935,0.0
97117,2020-03-31,GO,Águas Lindas de Goiás,city,1,0,4,False,212440.0,217698.0,5200258.0,0.45935,0.0
97118,2020-03-30,GO,Águas Lindas de Goiás,city,1,0,3,False,212440.0,217698.0,5200258.0,0.45935,0.0
97119,2020-03-29,GO,Águas Lindas de Goiás,city,1,0,2,False,212440.0,217698.0,5200258.0,0.45935,0.0
97120,2020-03-28,GO,Águas Lindas de Goiás,city,1,0,1,False,212440.0,217698.0,5200258.0,0.45935,0.0

In [29]:
data.drop(["date","state","city","place_type","is_last"], axis = 1).corr()

,confirmed,deaths,order_for_place,estimated_population_2019,estimated_population,city_ibge_code,confirmed_per_100k_inhabitants,death_rate
confirmed,1.000000,0.992515,0.119075,0.769217,0.769230,-0.740975,0.085365,-0.004473
deaths,0.992515,1.000000,0.119941,0.739452,0.739445,-0.707940,0.082949,-0.001461
order_for_place,0.119075,0.119941,1.000000,0.034784,0.034813,-0.024183,0.741258,-0.063731
estimated_population_2019,0.769217,0.739452,0.034784,1.000000,1.000000,-0.972132,0.005987,-0.001305
estimated_population,0.769230,0.739445,0.034813,1.000000,1.000000,-0.972079,0.006004,-0.001315
city_ibge_code,-0.740975,-0.707940,-0.024183,-0.972132,-0.972079,1.000000,-0.001197,0.002731
confirmed_per_100k_inhabitants,0.085365,0.082949,0.741258,0.005987,0.006004,-0.001197,1.000000,-0.080976
death_rate,-0.004473,-0.001461,-0.063731,-0.001305,-0.001315,0.002731,-0.080976,1.000000

In [30]:
estados = data.loc[data.place_type == 'state']
estados_go = estados.loc[data.state == 'GO']
estados_go_casos = estados_go.groupby('date')['confirmed'].sum().reset_index()
estados_go_casos.tail()

           date  confirmed
468  2021-06-23     664321
469  2021-06-24     667262
470  2021-06-25     670527
471  2021-06-26     670784
472  2021-06-27     671228

In [31]:
estados_go_casos_previsao = estados_go_casos
estados_go_casos_previsao.columns = ['ds','y']
estados_go_casos_previsao.tail()

             ds       y
468  2021-06-23  664321
469  2021-06-24  667262
470  2021-06-25  670527
471  2021-06-26  670784
472  2021-06-27  671228

In [32]:
# Criar instância do Prophet
modelProphet = ph.Prophet()
# Treinamento do modelos
modelProphet.fit(estados_go_casos_previsao)
# Definição de futuro para a realização da previsão
futuro = modelProphet.make_future_dataframe(30)
# Previsão dentro de um cenário futuro
previsao = modelProphet.predict(futuro)
# Plotando o resultado
fig = modelProphet.plot(previsao)

AttributeError: 'Prophet' object has no attribute 'stan_backend'

In [25]:
cidade_goiania_mortes = data.loc[data.place_type=='city'].loc[data.city=='Goiânia'].groupby('date')['deaths'].sum().reset_index()
cidade_goiania_mortes.columns = ['ds','y']

modelProphet = ph.Prophet()
modelProphet.fit(cidade_goiania_mortes)
futuro = modelProphet.make_future_dataframe(60)
previsao = modelProphet.predict(futuro)
fig = modelProphet.plot(previsao)

AttributeError: 'Prophet' object has no attribute 'stan_backend'